### ISSUE TITLE
хули код сложный

### ISSUE THREAD

**Issue by kisman2000** [moneymod/moneymod#12]
БЛЯТЬ А ХУЛИ ТАКОЙ КОД КРУТОЙ И СЛОЖНЫЙ МНЕ ПАСТИТЬ НЕ УДОБНО ПОМОГИТЕ СПАСИТЕ ПОЖАЛУЙСТА Я НЕ МОГУ ЭТО СПАСТИТЬ ПАМАГИТЕЕЕ

**Comment by mr-nv** [comment]
завали ебало

**Comment by oyzipfile** [comment]
я запрещаю пастить манимод

**Comment by kisman2000** [comment]
я уже спастил, ты опоздал

**Comment by oyzipfile** [comment]
удали

**Comment by kisman2000** [comment]
нихатю

**Comment by ZenovJB** [comment]
я спастил са в троллгод и все ахуенно работает спасибо братва

**Comment by ZenovJB** [comment]
> я лох

красава

**Comment by kisman2000** [comment]
согл

**Comment by NCPUser** [comment]
хаахха
