### ISSUE TITLE
1

### ISSUE THREAD

**Issue by mag1steroff** [moneymod/moneymod#2]
Add-AntiSurrond и улучшить логику  
HoleFill
PopChams-как в футур бете 
ESP как в конасе 
Fix AutoCrystal- place delay 0 break delay 0 и еще хуйню с энвилами и yaw step
Notify
Pop Counter 
Burrow-улучшить буроу байпасс 
AutoTrap
ShaderESP-добавить больше модов(я те скинул каттун) 
AutoEz
IRC И IRCBACKUP и еще чтоб когда нажимал на бекап у челов появлялся вэйпоинт 
FastXp 
Trails
CustomTotem(тотем гитлера)
GlowESP на предметы 
Capes
Speed
AutoMine
AutoArmor

**Comment by ZenovJB** [comment]
Add-AntiSurrond и улучшить логику
HoleFill
PopChams-как в футур бете
ESP как в конасе
Fix AutoCrystal- place delay 0 break delay 0 и еще хуйню с энвилами и yaw step
Notify
Pop Counter
Burrow-улучшить буроу байпасс
AutoTrap
ShaderESP-добавить больше модов(я те скинул каттун)
AutoEz
IRC И IRCBACKUP и еще чтоб когда нажимал на бекап у челов появлялся вэйпоинт
FastXp
Trails
CustomTotem(тотем гитлера)
GlowESP на предметы
Capes
Speed
AutoMine
AutoArmor

**Comment by u3o** [comment]
> Add-AntiSurrond и улучшить логику HoleFill PopChams-как в футур бете ESP как в конасе Fix AutoCrystal- place delay 0 break delay 0 и еще хуйню с энвилами и yaw step Notify Pop Counter Burrow-улучшить буроу байпасс AutoTrap ShaderESP-добавить больше модов(я те скинул каттун) AutoEz IRC И IRCBACKUP и еще чтоб когда нажимал на бекап у челов появлялся вэйпоинт FastXp Trails CustomTotem(тотем гитлера) GlowESP на предметы Capes Speed AutoMine AutoArmor

Зачем ты так унижаешь жестоко

**Comment by ZenovJB** [comment]
> > Add-AntiSurrond и улучшить логику HoleFill PopChams-как в футур бете ESP как в конасе Fix AutoCrystal- place delay 0 break delay 0 и еще хуйню с энвилами и yaw step Notify Pop Counter Burrow-улучшить буроу байпасс AutoTrap ShaderESP-добавить больше модов(я те скинул каттун) AutoEz IRC И IRCBACKUP и еще чтоб когда нажимал на бекап у челов появлялся вэйпоинт FastXp Trails CustomTotem(тотем гитлера) GlowESP на предметы Capes Speed AutoMine AutoArmor
> 
> Зачем ты так унижаешь жестоко

за что братан
